apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Values.app.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
data:
  DB_PATH: {{ .Values.config.DB_PATH | quote }}
