apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
