{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-data" .Values.app.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
